const canvas=document.getElementById('map'),ctx=canvas.getContext('2d');
const DAY_MIN=1440, SHIP_MAX=32400, AIR_MAX=9225, TOTAL_AIR=70;
const state={time:0,speed:1,paused:false,camera:{x:0,y:0,zoom:0.72},carrier:{x:0,y:0,hp:800,shipFuel:SHIP_MAX,airFuel:AIR_MAX,throttle:60},money:1000,rep:0,selected:null,route:[],mission:{area:null,intercept:null}};
const islands=[
 {id:'guam',name:'Guam',x:-650,y:40,side:'us',morale:100,size:125},
 {id:'wake',name:'Wake Island',x:-430,y:-150,side:'us',morale:100,size:80},
 {id:'midway',name:'Midway',x:-950,y:-310,side:'us',morale:100,size:75},
 {id:'japan1',name:'Japanese Home Islands',x:900,y:-300,side:'jp',morale:100,size:180},
 {id:'palau',name:'Palau',x:250,y:250,side:'jp',morale:100,size:90},
 {id:'truck',name:'Truk',x:40,y:30,side:'jp',morale:100,size:90},
 {id:'ph',name:'Philippines',x:-120,y:420,side:'jp',morale:100,size:135},
 {id:'neutral',name:'Neutral Territory',x:450,y:430,side:'neutral',morale:100,size:110}
];
const ships=[
 {id:'dd1',type:'Destroyer',x:-30,y:-40,hp:300,max:300,side:'jp',speed:6},
 {id:'dd2',type:'Destroyer',x:20,y:-15,hp:300,max:300,side:'jp',speed:6},
 {id:'cr1',type:'Cruiser',x:270,y:-20,hp:600,max:600,side:'jp',speed:6},
 {id:'sub1',type:'Submarine',x:440,y:100,hp:100,max:100,side:'jp',speed:10,submerged:true,surfaceTimer:0},
 {id:'patrol',type:'Patrol Boat',x:610,y:170,hp:50,max:50,side:'jp',speed:12}
];
let escorts=[{id:'escort1',type:'Destroyer Escort',x:-12,y:22,hp:300,max:300,side:'us',speed:6},{id:'escort2',type:'Destroyer Escort',x:12,y:22,hp:300,max:300,side:'us',speed:6}];
function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',resize);resize();
function worldToScreen(x,y){return {x:(x-state.camera.x)*state.camera.zoom+innerWidth/2,y:(y-state.camera.y)*state.camera.zoom+innerHeight/2}}function screenToWorld(x,y){return {x:(x-innerWidth/2)/state.camera.zoom+state.camera.x,y:(y-innerHeight/2)/state.camera.zoom+state.camera.y}}
function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);ctx.fillStyle='#0b3349';ctx.fillRect(0,0,innerWidth,innerHeight);drawGrid();drawFog();islands.forEach(drawIsland);ships.forEach(drawShip);escorts.forEach(drawShip);drawCarrier();drawRoute();}
function drawGrid(){ctx.strokeStyle='rgba(115,160,177,.09)';ctx.lineWidth=1;const step=100*state.camera.zoom;for(let x=(-state.camera.x*state.camera.zoom+innerWidth/2)%step;x<innerWidth;x+=step){ctx.beginPath();ctx.moveTo(x,58);ctx.lineTo(x,innerHeight-64);ctx.stroke()}for(let y=(-state.camera.y*state.camera.zoom+innerHeight/2)%step;y<innerHeight;y+=step){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(innerWidth,y);ctx.stroke()}}
function drawFog(){ctx.save();ctx.globalAlpha=.25;ctx.strokeStyle='#062238';ctx.lineWidth=2;for(let x=-innerHeight;x<innerWidth+innerHeight;x+=28){ctx.beginPath();ctx.moveTo(x,58);ctx.lineTo(x+innerHeight-58,innerHeight-64);ctx.stroke()}ctx.restore()}
function drawIsland(i){const p=worldToScreen(i.x,i.y),r=i.size*state.camera.zoom*.45;ctx.beginPath();ctx.ellipse(p.x,p.y,r,r*.65,0,0,Math.PI*2);ctx.fillStyle=i.side==='us'?'#285d77':i.side==='jp'?'#733b43':'#656b70';ctx.fill();ctx.strokeStyle='#d1d9dc';ctx.stroke();ctx.fillStyle='#fff';ctx.font='bold 11px system-ui';ctx.textAlign='center';ctx.fillText(i.name,p.x,p.y-r-7);if(i.side==='jp'&&i.morale<100){ctx.fillStyle='#111';ctx.fillRect(p.x-r,p.y+r+6,r*2,5);ctx.fillStyle='#bd934e';ctx.fillRect(p.x-r,p.y+r+6,r*2*i.morale/100,5)}}
function drawShip(s){const p=worldToScreen(s.x,s.y),r=Math.max(4,10*state.camera.zoom);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(.2);ctx.fillStyle=s.side==='us'?'#b7c5c9':'#777d82';ctx.fillRect(-r*1.7,-r*.55,r*3.4,r*1.1);ctx.fillStyle=s.type==='Battleship'||s.type==='Carrier'?'#343a3e':'#42494d';ctx.fillRect(-r*.7,-r*1.1,r*1.1,r*.6);ctx.restore();ctx.fillStyle='#fff';ctx.font='9px system-ui';ctx.textAlign='center';ctx.fillText(s.type,p.x,p.y-r-4);}
function drawCarrier(){const p=worldToScreen(state.carrier.x,state.carrier.y),r=18*state.camera.zoom;ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle='#d2d9dc';ctx.fillRect(-r*2,-r*.7,r*4,r*1.4);ctx.fillStyle='#3d474c';ctx.fillRect(-r*1.4,-r*1.1,r*2.8,r*.35);ctx.fillStyle='#a5b3b8';ctx.fillRect(-r*.4,-r*.55,r*1.2,r*.3);ctx.restore();ctx.fillStyle='#fff';ctx.font='bold 11px system-ui';ctx.textAlign='center';ctx.fillText('USS CARRIER',p.x,p.y-r-8)}
function drawRoute(){if(state.route.length){ctx.strokeStyle='#d7b65c';ctx.lineWidth=2;ctx.beginPath();let p=worldToScreen(state.carrier.x,state.carrier.y);ctx.moveTo(p.x,p.y);state.route.forEach(q=>{let s=worldToScreen(q.x,q.y);ctx.lineTo(s.x,s.y)});ctx.stroke();state.route.forEach(q=>{let s=worldToScreen(q.x,q.y);ctx.beginPath();ctx.arc(s.x,s.y,4,0,Math.PI*2);ctx.fillStyle='#d7b65c';ctx.fill()})}}
function update(dt){if(state.paused)return;state.time+=dt*state.speed;const mins=dt*state.speed;const throttle=state.carrier.throttle/100;const shipRate=7.5*Math.max(.15,Math.abs(throttle));state.carrier.shipFuel=Math.max(0,state.carrier.shipFuel-shipRate*mins);moveCarrier(mins);if(state.carrier.shipFuel<=0)state.carrier.throttle=0;updateEscorts();updateSubs(mins);updateEnemyMovement(mins);renderUI()}
function moveCarrier(mins){if(!state.route.length||state.carrier.throttle===0)return;const target=state.route[0],dx=target.x-state.carrier.x,dy=target.y-state.carrier.y,d=Math.hypot(dx,dy);const speed=6*(state.carrier.throttle/100);const step=speed*mins;if(d<=step){state.carrier.x=target.x;state.carrier.y=target.y;state.route.shift()}else{state.carrier.x+=dx/d*step;state.carrier.y+=dy/d*step}}
function updateEscorts(){escorts.forEach((e,i)=>{const ang=(i?1:-1)*Math.PI/2;const tx=state.carrier.x+Math.cos(ang)*25,ty=state.carrier.y+Math.sin(ang)*25;e.x+=(tx-e.x)*.06;e.y+=(ty-e.y)*.06})}
function updateSubs(mins){ships.filter(s=>s.type==='Submarine').forEach(s=>{if(!s.submerged){s.surfaceTimer+=mins;if(s.surfaceTimer>=30){s.submerged=true;s.surfaceTimer=0}}})}
function updateEnemyMovement(mins){ships.filter(s=>s.side==='jp').forEach(s=>{const target=state.carrier;const dx=target.x-s.x,dy=target.y-s.y,d=Math.hypot(dx,dy);if(d<600){s.x+=dx/d*s.speed*mins*.1;s.y+=dy/d*s.speed*mins*.1}})}
function renderUI(){const day=Math.floor(state.time/DAY_MIN)+1,dayMin=state.time%DAY_MIN,h=Math.floor(dayMin/60),m=Math.floor(dayMin%60);document.getElementById('clock').textContent=`Day ${day} · ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;document.getElementById('hull').textContent=`${Math.round(state.carrier.hp)} / 800`;document.getElementById('shipFuel').textContent=`${Math.round(state.carrier.shipFuel).toLocaleString()} / 32,400`;document.getElementById('airFuel').textContent=`${Math.round(state.carrier.airFuel).toLocaleString()} / 9,225`;document.getElementById('money').textContent='$'+state.money.toLocaleString();document.getElementById('rep').textContent=Math.floor(state.rep);document.getElementById('hullBar').style.width=(state.carrier.hp/800*100)+'%';document.getElementById('shipFuelBar').style.width=(state.carrier.shipFuel/SHIP_MAX*100)+'%';document.getElementById('airFuelBar').style.width=(state.carrier.airFuel/AIR_MAX*100)+'%';document.getElementById('throttleVal').textContent=state.carrier.throttle+'%';}
function selectObject(o){state.selected=o;const t=document.getElementById('selectedText'),a=document.getElementById('selectedActions');a.innerHTML='';if(o===state.carrier){t.innerHTML='<b>USS Carrier</b><br>800 HP · 6 mi/s maximum<br>2 destroyer escorts';const b=document.createElement('button');b.className='wide';b.textContent='SET WAYPOINT';b.onclick=()=>t.innerHTML='<b>Carrier selected.</b><br>Left-click the ocean to add waypoints.';a.appendChild(b)}else if(o){t.innerHTML=`<b>${o.name||o.type}</b><br>${o.type||'Island'}<br>${o.hp?`${o.hp}/${o.max} HP`:o.side==='jp'?'Enemy territory':'Friendly territory'}`;}}
canvas.addEventListener('click',e=>{if(e.clientY<60||e.clientY>innerHeight-70)return;const w=screenToWorld(e.clientX,e.clientY);if(state.selected===state.carrier){state.route.push(w);return}let nearest=null,best=Infinity;[...islands,...ships,...escorts].forEach(o=>{const d=Math.hypot(w.x-o.x,w.y-o.y);if(d<best){best=d;nearest=o}});if(nearest&&best<100/state.camera.zoom)selectObject(nearest);else{selectObject(state.carrier);state.route.push(w)}});
canvas.addEventListener('contextmenu',e=>{e.preventDefault();const w=screenToWorld(e.clientX,e.clientY);state.route=[w];selectObject(state.carrier)});
addEventListener('keydown',e=>{const k=e.key.toLowerCase();const step=100/state.camera.zoom;if(k==='w')state.camera.y-=step;if(k==='s')state.camera.y+=step;if(k==='a')state.camera.x-=step;if(k==='d')state.camera.x+=step});
canvas.addEventListener('wheel',e=>{e.preventDefault();state.camera.zoom=Math.max(.25,Math.min(2.2,state.camera.zoom*(e.deltaY<0?1.1:.91)))},{passive:false});
document.querySelectorAll('.speed').forEach(b=>b.onclick=()=>{state.speed=+b.dataset.speed;document.querySelectorAll('.speed').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
document.getElementById('throttle').oninput=e=>state.carrier.throttle=+e.target.value;document.getElementById('missionBtn').onclick=()=>{state.paused=true;document.getElementById('missionModal').classList.remove('hidden');document.getElementById('missionStatus').textContent='Select the mission area on the map.'};document.getElementById('closeMission').onclick=()=>{state.paused=false;document.getElementById('missionModal').classList.add('hidden')};document.getElementById('refuelBtn').onclick=()=>{state.carrier.shipFuel=SHIP_MAX;state.carrier.airFuel=AIR_MAX;renderUI()};
function loop(t){if(!loop.last)loop.last=t;const dt=Math.min(.1,(t-loop.last)/1000);loop.last=t;update(dt);draw();requestAnimationFrame(loop)}renderUI();selectObject(state.carrier);requestAnimationFrame(loop);
