const canvas=document.getElementById('map'),ctx=canvas.getContext('2d');
const DAY_MIN=1440,SHIP_MAX=32400,AIR_MAX=9225;
const state={time:0,speed:1,paused:false,camera:{x:-250,y:0,zoom:.72,vx:0,vy:0},carrier:{x:-600,y:0,hp:800,shipFuel:SHIP_MAX,airFuel:AIR_MAX,throttle:60},money:1000,rep:0,selected:null,route:[],keys:{},mission:{area:null,intercept:null,active:false},fog:new Map(),lastReal:performance.now()};
const islands=[
{id:'hawaii',name:'Hawaii',x:-1100,y:20,side:'us',size:120},{id:'midway',name:'Midway',x:-1350,y:-260,side:'us',size:75},{id:'wake',name:'Wake Island',x:-850,y:-150,side:'us',size:70},{id:'guam',name:'Guam',x:-520,y:90,side:'us',size:115},
{id:'palau',name:'Palau',x:40,y:260,side:'jp',size:75},{id:'truck',name:'Truk',x:250,y:40,side:'jp',size:85},{id:'saipan',name:'Saipan',x:480,y:-120,side:'jp',size:70},{id:'iwo',name:'Iwo Jima',x:690,y:-260,side:'jp',size:62},{id:'okinawa',name:'Okinawa',x:820,y:-70,side:'jp',size:85},{id:'japan',name:'Japan',x:1050,y:-250,side:'jp',size:165},
{id:'philippines',name:'Philippines',x:-30,y:520,side:'jp',size:135},{id:'formosa',name:'Formosa',x:610,y:210,side:'jp',size:70},{id:'solomons',name:'Solomons',x:-210,y:300,side:'jp',size:100},{id:'newguinea',name:'New Guinea',x:-400,y:480,side:'neutral',size:145},{id:'rabaul',name:'Rabaul',x:-40,y:380,side:'jp',size:70},{id:'neutral',name:'Neutral Islands',x:300,y:520,side:'neutral',size:105}
];
const ships=[
{id:'dd1',type:'Destroyer',x:150,y:-20,hp:300,max:300,side:'jp',speed:6},{id:'dd2',type:'Destroyer',x:190,y:10,hp:300,max:300,side:'jp',speed:6},{id:'cr1',type:'Cruiser',x:340,y:-70,hp:600,max:600,side:'jp',speed:6},{id:'bb1',type:'Battleship',x:560,y:20,hp:1200,max:1200,side:'jp',speed:3},{id:'patrol',type:'Patrol Boat',x:430,y:250,hp:50,max:50,side:'jp',speed:12},{id:'sub1',type:'Submarine',x:300,y:300,hp:100,max:100,side:'jp',speed:10,submerged:true,surfaceTimer:0},{id:'trader1',type:'Trader',x:170,y:380,hp:100,max:100,side:'jp',speed:6,route:[{x:170,y:380},{x:620,y:200}]},{id:'trader2',type:'Trader',x:560,y:-140,hp:100,max:100,side:'jp',speed:6,route:[{x:560,y:-140},{x:950,y:-230}]}
];
const escorts=[{id:'escort1',type:'Destroyer Escort',x:-575,y:-25,hp:300,max:300,side:'us',speed:6},{id:'escort2',type:'Destroyer Escort',x:-575,y:25,hp:300,max:300,side:'us',speed:6}];
const air={scout:10,fighter:40,bomber:20};
const detected=new Map();
function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',resize);resize();
function worldToScreen(x,y){return{x:(x-state.camera.x)*state.camera.zoom+innerWidth/2,y:(y-state.camera.y)*state.camera.zoom+innerHeight/2}}
function screenToWorld(x,y){return{x:(x-innerWidth/2)/state.camera.zoom+state.camera.x,y:(y-innerHeight/2)/state.camera.zoom+state.camera.y}}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function visible(o){if(o.side==='us'||o===state.carrier)return true;return detected.has(o.id)}
function updateDetection(){const radius=520;ships.forEach(s=>{if(s.type==='Submarine'&&s.submerged){if(dist(s,state.carrier)>radius)return}if(dist(s,state.carrier)<=radius||(s.type==='Submarine'&&!s.submerged&&dist(s,state.carrier)<=radius)){detected.set(s.id,performance.now())}});[...detected].forEach(([id,t])=>{if(performance.now()-t>300000)detected.delete(id)})}
function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);ctx.fillStyle='#0b3a55';ctx.fillRect(0,0,innerWidth,innerHeight);drawSeaGrid();islands.forEach(drawIsland);ships.forEach(s=>visible(s)&&drawShip(s));escorts.forEach(drawShip);drawCarrier();drawRoute();drawDetection();drawMissionMarkers();drawFog();}
function drawSeaGrid(){ctx.strokeStyle='rgba(130,185,205,.07)';ctx.lineWidth=1;const step=100*state.camera.zoom;let ox=(-state.camera.x*state.camera.zoom+innerWidth/2)%step,oy=(-state.camera.y*state.camera.zoom+innerHeight/2)%step;for(let x=ox;x<innerWidth;x+=step){ctx.beginPath();ctx.moveTo(x,60);ctx.lineTo(x,innerHeight-65);ctx.stroke()}for(let y=oy+60;y<innerHeight-65;y+=step){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(innerWidth,y);ctx.stroke()}}
function drawFog(){ctx.save();ctx.beginPath();ctx.rect(0,60,innerWidth,innerHeight-125);ctx.clip();ctx.globalAlpha=.28;ctx.strokeStyle='#062238';ctx.lineWidth=2;for(let x=-innerHeight;x<innerWidth+innerHeight;x+=28){ctx.beginPath();ctx.moveTo(x,60);ctx.lineTo(x+innerHeight,innerHeight-65);ctx.stroke()}ctx.restore()}
function drawDetection(){const p=worldToScreen(state.carrier.x,state.carrier.y);ctx.save();ctx.strokeStyle='rgba(100,220,255,.16)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,520*state.camera.zoom,0,Math.PI*2);ctx.stroke();ctx.restore()}
function drawIsland(i){const p=worldToScreen(i.x,i.y),r=i.size*state.camera.zoom*.45;ctx.save();ctx.translate(p.x,p.y);ctx.rotate((i.x+i.y)*.002);ctx.beginPath();for(let n=0;n<12;n++){const a=n*Math.PI*2/12,rr=r*(.72+.25*Math.sin(n*2.7+i.x));const x=Math.cos(a)*rr,y=Math.sin(a)*rr*.68;n?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.fillStyle=i.side==='us'?'#2e6e89':i.side==='jp'?'#7b3d46':'#626c70';ctx.fill();ctx.strokeStyle='#c9d5d8';ctx.stroke();ctx.restore();ctx.fillStyle='#fff';ctx.font='bold 10px system-ui';ctx.textAlign='center';ctx.fillText(i.name,p.x,p.y-r-6);if(i.side==='jp'&&i.morale<100){ctx.fillStyle='#111';ctx.fillRect(p.x-r,p.y+r+5,r*2,4);ctx.fillStyle='#d0a65b';ctx.fillRect(p.x-r,p.y+r+5,r*2*i.morale/100,4)}}
function drawShip(s){const p=worldToScreen(s.x,s.y),r=Math.max(5,10*state.camera.zoom);ctx.save();ctx.translate(p.x,p.y);let c=s.side==='us'?'#b8c7ca':'#737b80';ctx.fillStyle=c;ctx.strokeStyle='#1b2225';ctx.lineWidth=1.5;ctx.beginPath();if(s.type==='Battleship'){ctx.moveTo(-2.4*r,-.55*r);ctx.lineTo(2.4*r,-.55*r);ctx.lineTo(1.8*r,.65*r);ctx.lineTo(-1.8*r,.65*r)}else if(s.type==='Cruiser'){ctx.moveTo(-2*r,-.45*r);ctx.lineTo(2*r,-.45*r);ctx.lineTo(1.5*r,.55*r);ctx.lineTo(-1.5*r,.55*r)}else if(s.type==='Destroyer'||s.type==='Destroyer Escort'){ctx.moveTo(-2.2*r,-.3*r);ctx.lineTo(2.2*r,0);ctx.lineTo(-2.2*r,.3*r)}else if(s.type==='Patrol Boat'){ctx.moveTo(-1.5*r,-.7*r);ctx.lineTo(1.8*r,0);ctx.lineTo(-1.5*r,.7*r)}else if(s.type==='Submarine'){ctx.ellipse(0,0,2*r,.6*r,0,0,Math.PI*2)}else{ctx.rect(-2*r,-.55*r,4*r,1.1*r)}ctx.closePath();ctx.fill();ctx.stroke();if(s.type==='Battleship'){ctx.fillStyle='#343b3f';for(let n=-1;n<=1;n++){ctx.fillRect(n*r,-.9*r,.45*r,.35*r);ctx.fillRect(n*r,.55*r,.45*r,.35*r)}}else if(s.type==='Cruiser'){ctx.fillStyle='#343b3f';ctx.fillRect(-.3*r,-.85*r,.6*r,.35*r);ctx.fillRect(-.3*r,.5*r,.6*r,.35*r)}else if(s.type==='Submarine'){ctx.fillStyle='#31383b';ctx.fillRect(-.2*r,-1.0*r,.4*r,.7*r)}else if(s.type==='Trader'){ctx.fillStyle='#9a7b4f';ctx.fillRect(-.7*r,-.35*r,1.4*r,.7*r)}ctx.restore();ctx.fillStyle='#fff';ctx.font='9px system-ui';ctx.textAlign='center';ctx.fillText(s.type,p.x,p.y-r-5)}
function drawCarrier(){const p=worldToScreen(state.carrier.x,state.carrier.y),r=19*state.camera.zoom;ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle='#cbd5d8';ctx.fillRect(-2.5*r,-.7*r,5*r,1.4*r);ctx.fillStyle='#4b575c';ctx.fillRect(-1.7*r,-1.05*r,3.5*r,.3*r);ctx.fillStyle='#8e9ba0';ctx.fillRect(-.5*r,-.45*r,1*r,.3*r);ctx.restore();ctx.fillStyle='#fff';ctx.font='bold 11px system-ui';ctx.textAlign='center';ctx.fillText('USS CARRIER',p.x,p.y-r-8)}
function drawRoute(){if(!state.route.length)return;ctx.strokeStyle='#e2c05e';ctx.lineWidth=2;ctx.beginPath();let p=worldToScreen(state.carrier.x,state.carrier.y);ctx.moveTo(p.x,p.y);state.route.forEach(q=>{const s=worldToScreen(q.x,q.y);ctx.lineTo(s.x,s.y)});ctx.stroke();state.route.forEach(q=>{const s=worldToScreen(q.x,q.y);ctx.beginPath();ctx.arc(s.x,s.y,4,0,Math.PI*2);ctx.fillStyle='#e2c05e';ctx.fill()})}
function drawMissionMarkers(){if(state.mission.area){const p=worldToScreen(state.mission.area.x,state.mission.area.y);ctx.strokeStyle='#ffd35a';ctx.setLineDash([7,5]);ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,65*state.camera.zoom,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#ffd35a';ctx.fillText('MISSION',p.x,p.y-75*state.camera.zoom)}if(state.mission.intercept){const p=worldToScreen(state.mission.intercept.x,state.mission.intercept.y);ctx.strokeStyle='#68e0ff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,45*state.camera.zoom,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#68e0ff';ctx.fillText('INTERCEPT',p.x,p.y-55*state.camera.zoom)}}
function moveCarrier(mins){if(!state.route.length||state.carrier.throttle===0)return;const t=state.route[0],dx=t.x-state.carrier.x,dy=t.y-state.carrier.y,d=Math.hypot(dx,dy),speed=6*(state.carrier.throttle/100);const step=speed*mins;if(d<=step){state.carrier.x=t.x;state.carrier.y=t.y;state.route.shift()}else{state.carrier.x+=dx/d*step;state.carrier.y+=dy/d*step}}
function updateEscorts(){escorts.forEach((e,i)=>{const tx=state.carrier.x+(i?28:-28),ty=state.carrier.y+(i?28:-28);e.x+=(tx-e.x)*.08;e.y+=(ty-e.y)*.08})}
function updateEnemyMovement(mins){ships.filter(s=>s.side==='jp').forEach(s=>{if(s.type==='Trader'){const t=s.route[0];const d=dist(s,t);if(d<8){s.route.push(s.route.shift())}else{s.x+=(t.x-s.x)/d*s.speed*mins*.35;s.y+=(t.y-s.y)/d*s.speed*mins*.35}return}const d=dist(s,state.carrier);if(d<650){s.x+=(state.carrier.x-s.x)/d*s.speed*mins*.08;s.y+=(state.carrier.y-s.y)/d*s.speed*mins*.08}})}
function updateSubs(mins){ships.filter(s=>s.type==='Submarine').forEach(s=>{if(!s.submerged){s.surfaceTimer+=mins;if(s.surfaceTimer>=30){s.submerged=true;s.surfaceTimer=0}}})}
function updateCamera(dt){const k=state.keys;let x=0,y=0;if(k.w)y-=1;if(k.s)y+=1;if(k.a)x-=1;if(k.d)x+=1;const mag=Math.hypot(x,y)||1;const targetX=x/mag*420/Math.max(.45,state.camera.zoom),targetY=y/mag*420/Math.max(.45,state.camera.zoom);state.camera.vx+=(targetX-state.camera.vx)*Math.min(1,dt*9);state.camera.vy+=(targetY-state.camera.vy)*Math.min(1,dt*9);state.camera.x+=state.camera.vx*dt;state.camera.y+=state.camera.vy*dt}
function update(dt){updateCamera(dt);if(state.paused){renderUI();return}const mins=dt*state.speed;state.time+=mins;const throttle=Math.abs(state.carrier.throttle)/100;state.carrier.shipFuel=Math.max(0,state.carrier.shipFuel-7.5*Math.max(.15,throttle)*mins);moveCarrier(mins);updateEscorts();updateSubs(mins);updateEnemyMovement(mins);updateDetection();renderUI()}
function renderUI(){const day=Math.floor(state.time/DAY_MIN)+1,dm=state.time%DAY_MIN,h=Math.floor(dm/60),m=Math.floor(dm%60);clock.textContent=`Day ${day} · ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;hull.textContent=`${Math.round(state.carrier.hp)} / 800`;shipFuel.textContent=`${Math.round(state.carrier.shipFuel).toLocaleString()} / 32,400`;airFuel.textContent=`${Math.round(state.carrier.airFuel).toLocaleString()} / 9,225`;money.textContent='$'+state.money.toLocaleString();rep.textContent=state.rep;hullBar.style.width=state.carrier.hp/800*100+'%';shipFuelBar.style.width=state.carrier.shipFuel/SHIP_MAX*100+'%';airFuelBar.style.width=state.carrier.airFuel/AIR_MAX*100+'%';throttleVal.textContent=state.carrier.throttle+'%';scouts.textContent=air.scout+' / 10';fighters.textContent=air.fighter+' / 40';bombers.textContent=air.bomber+' / 20'}
function selectObject(o){state.selected=o;selectedActions.innerHTML='';if(o===state.carrier){selectedText.innerHTML='<b>USS Carrier</b><br>800 HP · 6 mi/s maximum<br>2 destroyer escorts'}else if(o){selectedText.innerHTML=`<b>${o.name||o.type}</b><br>${o.type||'Island'}<br>${o.hp?`${Math.round(o.hp)}/${o.max} HP`:o.side==='jp'?'Japanese territory':'U.S. territory'}`;if(o.side==='us'&&o.id){const b=document.createElement('button');b.className='wide';b.textContent='OPEN ISLAND STORE';b.onclick=openStore;b && selectedActions.appendChild(b)}}}
function nearestAt(w){let best=Infinity,hit=null;[...islands,...ships,...escorts].forEach(o=>{if(!visible(o))return;const d=dist(w,o);if(d<best){best=d;hit=o}});return{hit,best}}
canvas.addEventListener('click',e=>{if(e.clientY<58||e.clientY>innerHeight-65)return;const w=screenToWorld(e.clientX,e.clientY);if(state.mission.active){if(!state.mission.area){state.mission.area=w;missionStatus.textContent='Mission zone set. Now click the carrier intercept/return point.'}else if(!state.mission.intercept){state.mission.intercept=w;missionStatus.textContent='Both zones set. Choose aircraft quantities, then press ENGINES FREE.'}return}if(state.selected===state.carrier){state.route.push(w);return}const q=nearestAt(w);if(q.hit&&q.best<90/state.camera.zoom)selectObject(q.hit);else{selectObject(state.carrier);state.route.push(w)}});
canvas.addEventListener('contextmenu',e=>{e.preventDefault();if(state.mission.active)return;state.route=[screenToWorld(e.clientX,e.clientY)];selectObject(state.carrier)});
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if('wasd'.includes(k)){state.keys[k]=true;e.preventDefault()}});addEventListener('keyup',e=>{state.keys[e.key.toLowerCase()]=false});
canvas.addEventListener('wheel',e=>{e.preventDefault();state.camera.zoom=Math.max(.25,Math.min(2.4,state.camera.zoom*(e.deltaY<0?1.1:.91)))},{passive:false});
document.querySelectorAll('.speed').forEach(b=>b.onclick=()=>{state.speed=+b.dataset.speed;document.querySelectorAll('.speed').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
throttle.oninput=e=>state.carrier.throttle=+e.target.value;
missionBtn.onclick=()=>{state.paused=true;state.mission.active=true;state.mission.area=null;state.mission.intercept=null;missionModal.classList.remove('hidden');missionStatus.textContent='Click the map to choose the mission zone.'};
closeMission.onclick=()=>{state.paused=false;state.mission.active=false;missionModal.classList.add('hidden')};
enginesFree.onclick=()=>{const s=+scoutQty.value,f=+fighterQty.value,b=+bomberQty.value;if(!state.mission.area||!state.mission.intercept){missionStatus.textContent='Set both map zones first.';return}if(s+f+b===0){missionStatus.textContent='Choose at least one aircraft.';return}if(s>air.scout||f>air.fighter||b>air.bomber){missionStatus.textContent='Not enough aircraft available.';return}air.scout-=s;air.fighter-=f;air.bomber-=b;state.mission.active=false;missionModal.classList.add('hidden');state.paused=false;selectedText.innerHTML=`<b>Mission launched</b><br>${s} Scouts · ${f} Fighters · ${b} Dive Bombers`;renderUI()};
refuelBtn.onclick=()=>{state.carrier.shipFuel=SHIP_MAX;state.carrier.airFuel=AIR_MAX;renderUI()};
function openStore(){state.paused=true;storeModal.classList.remove('hidden')}
closeStore.onclick=()=>{state.paused=false;storeModal.classList.add('hidden')};
document.querySelectorAll('.buy').forEach(b=>b.onclick=()=>{const type=b.dataset.type,cost=+b.dataset.cost;if(state.money<cost){storeStatus.textContent='Not enough money.';return}state.money-=cost;if(type==='scout')air.scout++;if(type==='fighter')air.fighter++;if(type==='bomber')air.bomber++;storeStatus.textContent=`Purchased ${b.textContent.replace('BUY ','')}.`;renderUI()});
function loop(t){const dt=Math.min(.05,(t-state.lastReal)/1000);state.lastReal=t;update(dt);draw();requestAnimationFrame(loop)}
renderUI();selectObject(state.carrier);requestAnimationFrame(loop);
